### ISSUE TITLE
Camera Component

### ISSUE THREAD

**Issue by danielxbauer** [surfacers/what-ae-brick#2]

**Comment by bemayr** [comment]
Just did some research and [expo-camera](https://docs.expo.io/versions/latest/sdk/camera/) looks better than [react-native-camera](https://github.com/react-native-camera/react-native-camera) because they are looking for maintainers.
A few important resources to consider are:
- How to add features to the camera: https://github.com/react-native-camera/react-native-camera/tree/master/examples/advanced
- Masking the camera [stackoverflow-question](https://stackoverflow.com/questions/48510350/react-native-camera-with-a-transparent-view-for-barcode-scanner-mask)
  - https://www.npmjs.com/package/react-native-barcode-mask
  - https://github.com/ibitcy/react-native-hole-view
